<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateProgramFile>false</GenerateProgramFile>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ObservationGenerationTests.fs" />
    <Compile Include="CausalOperationExecutionTests.fs" />
    <Compile Include="CausalOperationBatchExecutionTests.fs" />
    <Compile Include="CausalLedgerTests.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Omokane.Core\Omokane.Core.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Expecto" Version="11.1.0" />
  </ItemGroup>

</Project>
